FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_PREFER_BINARY=1 \
    CUDA_HOME=/usr/local/cuda-11.8 \
    DEBCONF_NOWARNINGS=yes
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update \
    && apt-get -y upgrade \
    && apt-get install -y \
        poppler-utils \
        libpoppler-dev \
        wget \
        curl \
        git \
        ffmpeg \
        libsm6 \
        libxext6 \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* /var/tmp/*

WORKDIR /app

ADD . /app/

# RUN /root/.local/bin/uv sync
# RUN /root/.local/bin/uv pip install --no-build-isolation "git+https://github.com/facebookresearch/detectron2.git"

# ENTRYPOINT [ "/root/.local/bin/uv", "run", "server.py" ]
#
CMD ["bash"]
